name: Build CI

on:
  workflow_call:
  workflow_dispatch:

jobs:
  Build-kpm-midi:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0
      
      - name: Debug - Show current directory
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory listing:"
          ls -la
      
      - name: Install Compiler
        run: |
          curl -o arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf.tar.xz https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf.tar.xz
          tar -Jxf arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf.tar.xz
      
      - name: Build kpm-midi
        run: |
          export TARGET_COMPILE=`pwd`/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf/bin/aarch64-none-elf-
          
          # We are already in the kpm-midi directory
          echo "Current directory: $(pwd)"
          echo "Directory listing:"
          ls -la
          
          # Check if Makefile exists
          if [ ! -f "Makefile" ]; then
            echo "Error: Makefile not found"
            exit 1
          fi
          
          make
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            midi.kpm
          name: kpm-midi-artifact