name: Build CI

on:
  workflow_call:
  workflow_dispatch:

jobs:
  Build-kpm-midi:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0
      
      - name: Debug - List root directory
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing root directory:"
          ls -la
          echo "Listing all directories recursively:"
          find . -type d -not -path "./.git/*" | sort
      
      - name: Debug - Check Git status
        run: |
          echo "Git status:"
          git status
          echo "Git branch:"
          git branch -a
      
      - name: Install Compiler
        run: |
          curl -o arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf.tar.xz https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf.tar.xz
          tar -Jxf arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf.tar.xz
      
      - name: Build kpm-midi
        run: |
          export TARGET_COMPILE=`pwd`/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf/bin/aarch64-none-elf-
          # Try to find and enter kpm-midi directory
          if [ -d "kpm-midi" ]; then
            echo "Found kpm-midi in current directory"
            cd kpm-midi
          else
            echo "kpm-midi not in current directory, searching..."
            KPM_MIDI_DIR=$(find . -type d -name "kpm-midi" -not -path "./.git/*" | head -n 1)
            if [ -n "$KPM_MIDI_DIR" ] && [ -d "$KPM_MIDI_DIR" ]; then
              echo "Found kpm-midi directory at: $KPM_MIDI_DIR"
              cd "$KPM_MIDI_DIR"
            else
              echo "Error: kpm-midi directory not found"
              echo "Current directory: $(pwd)"
              echo "Directory listing:"
              ls -la
              exit 1
            fi
          fi
          
          echo "Current directory: $(pwd)"
          echo "Directory listing:"
          ls -la
          
          # Check if Makefile exists
          if [ ! -f "Makefile" ]; then
            echo "Error: Makefile not found in kpm-midi directory"
            exit 1
          fi
          
          make
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            */midi.kpm
          name: kpm-midi-artifact