name: Build CI

on:
  workflow_call:
  workflow_dispatch:

jobs:
  Build-kpm-midi:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0
      
      - name: Debug - List root directory
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing root directory:"
          ls -la
      
      - name: Debug - Find kpm-midi directory
        run: |
          echo "Searching for kpm-midi directory:"
          find . -type d -name "kpm-midi" 2>/dev/null || echo "kpm-midi directory not found"
      
      - name: Install Compiler
        run: |
          curl -o arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf.tar.xz https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf.tar.xz
          tar -Jxf arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf.tar.xz
      
      - name: Build kpm-midi
        run: |
          export TARGET_COMPILE=`pwd`/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf/bin/aarch64-none-elf-
          # Try to find and enter kpm-midi directory
          if [ -d "kpm-midi" ]; then
            cd kpm-midi
          else
            KPM_MIDI_DIR=$(find . -type d -name "kpm-midi" | head -n 1)
            if [ -n "$KPM_MIDI_DIR" ]; then
              cd "$KPM_MIDI_DIR"
            else
              echo "Error: kpm-midi directory not found"
              exit 1
            fi
          fi
          make
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            kpm-midi/midi.kpm
          name: kpm-midi-artifact