name: Build CI

on:
  workflow_call:
  workflow_dispatch:

jobs:
  Build-kpm-phone-monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out kpm-phone-monitor
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0
          path: kpm-phone-monitor
      
      - name: Clone SukiSU_KernelPatch_patch
        run: |
          cd ..
          git clone https://github.com/SukiSU-Ultra/SukiSU_KernelPatch_patch.git
      
      - name: Debug - Show directory structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory listing:"
          ls -la
          echo "Parent directory listing:"
          ls -la ..
      
      - name: Install Compiler
        run: |
          curl -o arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf.tar.xz https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf.tar.xz
          tar -Jxf arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf.tar.xz
      
      - name: Build kpm-phone-monitor
        run: |
          export TARGET_COMPILE=`pwd`/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf/bin/aarch64-none-elf-
          export KP_DIR=`pwd`/../SukiSU_KernelPatch_patch
          
          cd kpm-phone-monitor
          echo "Current directory: $(pwd)"
          echo "Directory listing:"
          ls -la
          
          # Check if Makefile exists
          if [ ! -f "Makefile" ]; then
            echo "Error: Makefile not found"
            exit 1
          fi
          
          make
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            kpm-phone-monitor/phone-monitor.kpm
          name: kpm-phone-monitor-artifact